- name: provision mysql instance - Initialise
  hosts: "localhost"
  gather_facts: yes
  become: yes
  no_log: false
  vars:
    ansible_python_interpreter: /usr/bin/python3
    PATH_TO_CERTS: "{{ lookup('env','MYSQL_PATH_TO_CERTS')|default('/tmp', true) }}"
    MYSQL_PATH_TO_CONF: "{{ lookup('env','MYSQL_PATH_TO_CONF')|default('/tmp', true) }}"
    DB_LOCAL_USERNAME: "{{ lookup('env','MYSQL_LOCAL_USER') }}"
    DB_LOCAL_USERPASS: "{{ lookup('env','MYSQL_LOCAL_USER_PASS') }}"
  tasks:
    - debug:
        msg: "New db name is {{ MYSQL_PATH_TO_CONF }}"
    - debug:
        msg: "New db user is {{ DB_LOCAL_USERNAME }}"
    - debug:
        msg: "New db user pass is {{ DB_LOCAL_USERPASS }}"
    - name: Update APT Package repository cache
      apt:
        update_cache: True
        state: latest
    - name: Install MySQL server on Ubuntu 20.04 LTS
      apt:
        name: mysql-server
        state: present
    - name: Install MySQL client on Ubuntu 20.04 LTS
      apt:
        name: mysql-client
        state: present
    - name: Make sure mysql service is running
      service:
        name: mysql
        state: started
        enabled: True
    - name: Install python3-pymysql library
      apt:
        name: python3-pymysql
        state: present
    - name: Copy mysqld.cnf file with updated bind-address
      copy: 
        src: "{{ MYSQL_PATH_TO_CONF }}/mysqld.cnf"
        dest: /etc/mysql/mysql.conf.d/mysqld.cnf
    - name: Copy mysql ca-cert to etc folder
      copy:
        src: "{{ PATH_TO_CERTS }}/mysql-cacert.pem"
        dest: "/var/lib/mysql/selfsigned-cacert.pem"
        owner: "mysql"
        group: "mysql"
        mode: 0600
      no_log: false
    - name: Copy mysql-server-cert to etc folder
      copy:
        src: "{{ PATH_TO_CERTS }}/mysql-server-cert.pem"
        dest: "/var/lib/mysql/selfsigned-server-cert.pem"
        owner: "mysql"
        group: "mysql"
        mode: 0600
      no_log: false
    - name: Copy mysql-server-key to etc folder
      copy:
        src: "{{ PATH_TO_CERTS }}/mysql-server-key.pem"
        dest: "/var/lib/mysql/selfsigned-server-key.pem"
        owner: "mysql"
        group: "mysql"
        mode: 0600
      no_log: false
    - name: Restart service mysql, in all cases
      service:
        name: mysql
        state: restarted
    - name: Make sure mysql service is running
      service:
        name: mysql
        state: started
        enabled: True
    - name: Change the authentication plugin of MySQL root user to mysql_native_password
      shell: mysql -u root -e 'UPDATE mysql.user SET plugin="mysql_native_password" WHERE user="root" AND host="localhost"'
    - name: Flush Privileges
      shell: mysql -u root -e 'FLUSH PRIVILEGES'
    - name: Create local root user
      community.mysql.mysql_user:
        login_host: "localhost"
        login_user: "root"
        login_password: ""
        name: "{{ DB_LOCAL_USERNAME }}"
        password: "{{ DB_LOCAL_USERPASS }}"
        state: present
      no_log: FALSE
